# Generated by Django 4.2.4 on 2023-09-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="items",
            field=models.ManyToManyField(blank=True, related_name="inventories", to="items.useritem"),
        ),
    ]
