# Generated by Django 4.2.4 on 2023-09-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        ("dashboard", "0002_inventory_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="usershop",
            name="items",
            field=models.ManyToManyField(blank=True, related_name="shops", to="items.useritem"),
        ),
    ]
