# Generated by Django 4.2.4 on 2023-09-04 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_remove_useritem_user"),
        ("dashboard", "0006_alter_usershop_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="items",
        ),
        migrations.AddField(
            model_name="inventory",
            name="items",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory",
                to="items.useritem",
            ),
        ),
    ]
