# Generated by Django 4.2.4 on 2023-09-04 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_remove_inventory_items_inventory_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="items",
        ),
        migrations.RemoveField(
            model_name="usershop",
            name="items",
        ),
    ]
