# Generated by Django 4.2.4 on 2023-09-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0002_inventory_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovesModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("attack_amount", models.IntegerField(blank=True, null=True)),
                ("defense_amount", models.IntegerField(blank=True, null=True)),
                ("accuracy", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PetModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1", "TYPE 1"),
                            ("2", "TYPE 2"),
                            ("3", "TYPE 3"),
                            ("4", "TYPE 4"),
                            ("5", "TYPE 5"),
                            ("6", "TYPE 6"),
                            ("7", "TYPE 7"),
                            ("8", "TYPE 8"),
                        ],
                        default=1,
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pets", to="dashboard.dashboard"
                    ),
                ),
                ("moves", models.ManyToManyField(blank=True, related_name="pets", to="pets.movesmodel")),
            ],
        ),
        migrations.CreateModel(
            name="PetStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hp_now", models.IntegerField(default=0)),
                ("hp_total", models.IntegerField(default=0)),
                ("attack", models.IntegerField(default=0)),
                ("defense", models.IntegerField(default=0)),
                ("speed", models.IntegerField(default=0)),
                ("special_attack", models.IntegerField(default=0)),
                ("special_defense", models.IntegerField(default=0)),
                ("accuracy", models.IntegerField(default=0)),
                ("evasion", models.IntegerField(default=0)),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stats", to="pets.petmodel"
                    ),
                ),
            ],
        ),
    ]
