# Generated by Django 4.2.4 on 2023-09-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petmodel",
            name="favorite",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
