# Generated by Django 4.2.4 on 2023-09-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_petmodel_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=80)),
                (
                    "type_1",
                    models.CharField(
                        choices=[
                            ("1", "normal"),
                            ("2", "fire"),
                            ("3", "water"),
                            ("4", "grass"),
                            ("5", "electric"),
                            ("6", "fighting"),
                            ("7", "poison"),
                            ("8", "ground"),
                            ("9", "psychic"),
                            ("10", "ghost"),
                            ("11", "dragon"),
                            ("12", "dark"),
                            ("13", "fairy"),
                        ],
                        default="1",
                        max_length=2,
                    ),
                ),
                (
                    "type_2",
                    models.CharField(
                        choices=[
                            ("1", "normal"),
                            ("2", "fire"),
                            ("3", "water"),
                            ("4", "grass"),
                            ("5", "electric"),
                            ("6", "fighting"),
                            ("7", "poison"),
                            ("8", "ground"),
                            ("9", "psychic"),
                            ("10", "ghost"),
                            ("11", "dragon"),
                            ("12", "dark"),
                            ("13", "fairy"),
                        ],
                        default="1",
                        max_length=2,
                    ),
                ),
                ("attack_damage", models.IntegerField(blank=True, null=True)),
                ("health", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
