# Generated by Django 4.2.4 on 2023-09-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_move"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MovesModel",
        ),
        migrations.AlterField(
            model_name="petmodel",
            name="moves",
            field=models.ManyToManyField(blank=True, related_name="pets", to="pets.move"),
        ),
    ]
