# Generated by Django 4.2.4 on 2023-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="description",
            field=models.CharField(default="test", max_length=190),
            preserve_default=False,
        ),
    ]
