# Generated by Django 4.2.4 on 2023-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0002_achievement_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="category",
            field=models.CharField(
                choices=[("1", "account"), ("2", "shop"), ("3", "inventory"), ("4", "pets")], default="1", max_length=1
            ),
        ),
    ]
