# Generated by Django 4.2.4 on 2023-09-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_alter_achievement_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="limit",
            field=models.IntegerField(default=1),
        ),
    ]
