# Generated by Django 4.2.4 on 2023-09-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_useritem_in_shop_shopitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="for_sale",
                to="items.useritem",
            ),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created",
                to="items.item",
            ),
        ),
    ]
