# Generated by Django 4.2.4 on 2023-09-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_alter_shopitem_item_alter_useritem_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="in_market",
            field=models.BooleanField(default=False),
        ),
    ]
