# Generated by Django 4.2.4 on 2023-09-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_remove_inventory_items_remove_usershop_items"),
        ("items", "0005_remove_useritem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="shop",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="shop", to="dashboard.usershop"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useritem",
            name="inventory",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="items", to="dashboard.inventory"
            ),
            preserve_default=False,
        ),
    ]
