# Generated by Django 4.2.4 on 2023-09-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0006_shopitem_shop_useritem_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChestItem",
            fields=[
                (
                    "useritem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="items.useritem",
                    ),
                ),
                ("random", models.IntegerField(default=30)),
            ],
            bases=("items.useritem",),
        ),
    ]
