# Generated by Django 4.2.4 on 2023-09-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0009_slugitem_remove_chestitem_random_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="probability",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
