# Generated by Django 4.2.4 on 2023-09-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0010_item_probability"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyItem",
            fields=[
                (
                    "useritem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="items.useritem",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
            ],
            bases=("items.useritem",),
        ),
    ]
