# Generated by Django 4.2.4 on 2023-09-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_delete_movesmodel_alter_petmodel_moves"),
        ("battle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("health", models.IntegerField(default=0)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="opponent", to="pets.petmodel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op_1",
                to="battle.opponent",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op_2",
                to="battle.opponent",
            ),
        ),
    ]
