# Generated by Django 4.2.4 on 2023-09-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0013_item_created_at_item_released_date_and_more"),
        ("pets", "0004_delete_movesmodel_alter_petmodel_moves"),
        ("battle", "0002_opponent_battle_opponent_1_battle_opponent_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="status",
            field=models.CharField(choices=[("1", "active"), ("2", "closed")], default="1", max_length=2),
        ),
        migrations.AddField(
            model_name="battleaction",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="battleaction",
            name="move",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="pets.move",
            ),
        ),
        migrations.AddField(
            model_name="battleaction",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="battle.opponent",
            ),
        ),
        migrations.AddField(
            model_name="battleaction",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="battle.opponent",
            ),
        ),
    ]
