# Generated by Django 4.2.4 on 2023-09-08 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("battle", "0003_battle_status_battleaction_item_battleaction_move_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="battle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="battleaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="battleaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
