# Generated by Django 4.2.4 on 2023-09-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgeritem",
            name="operation",
            field=models.CharField(choices=[("1", "adds"), ("2", "takes")], default="1", max_length=2),
        ),
        migrations.AddField(
            model_name="ledgeritem",
            name="type",
            field=models.CharField(
                choices=[("1", "system"), ("2", "shop"), ("3", "chest")], default="1", max_length=2
            ),
        ),
    ]
