# Generated by Django 4.2.4 on 2023-09-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_ledgeritem_operation_ledgeritem_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgeritem",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
